### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by zkjkak** [HAAClassic/TreeFormer#3]
Hello, I downloaded the dataset and code you provided, but when the data was loaded, I was prompted that the identitymap.npy file does not exist, and the dataset I downloaded also does not exist. Can you provide these files?
![图片](https://github.com/HAAClassic/TreeFormer/assets/81848995/77ee5a05-b8db-4ef6-90ac-028c81f8f0c6)

**Comment by HAAClassic** [comment]
Hi, yes you're right. I did not add it because it would greatly increase the size of the uploaded file. you can generate the density maps according to https://github.com/gjy3035/Awesome-Crowd-Counting. There are Matlab and Python codes here for generating density maps.

**Comment by zkjkak** [comment]
Thank you for your help, but I encountered a problem while running the MATLAB code you provided, and I am unable to solve it. I am not sure if you have encountered this problem before. Here is a screenshot of the problem.
![图片](https://github.com/HAAClassic/TreeFormer/assets/81848995/ae3a3916-767d-42d0-9bd2-e71dd2dcdc61)

**Comment by PemasiriAkila** [comment]
Hello, can you please let know the specific density map generation method you used.

**Comment by HAAClassic** [comment]
I optimize the file size and add the density maps too (https://drive.google.com/file/d/1xcjv8967VvvzcDM4aqAi7Corkb11T0i2/view?usp=drive_link).

**Comment by HAAClassic** [comment]
Hi, we follow [*] to generate the ground truth density maps from the tree locations using Gaussian functions.
* Zhang, Y., Zhou, D., Chen, S., Gao, S. and Ma, Y., 2016. Single-image crowd counting via multi-column convolutional neural network. In Proceedings of the IEEE conference on computer vision and pattern recognition (pp. 589-597).

**Comment by ghost** [comment]
Can i ask for how to label the dataset

**Comment by HAAClassic** [comment]
Hi, we annotated images manually from high-resolution Google Earth images.
