### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by zkjkak** [HAAClassic/TreeFormer#4]
Hello, in your paper, you used three datasets to verify the effectiveness of the model. Regarding the Jiangsu dataset and Yosemite dataset, based on the paper you cited, I have not found a way to publicly download these two datasets. How did you download them?
The second question is that in your paper, you divided the dataset into labeled and unlabeled data of 1:9 and 3:7. Can you provide this partition file?

**Comment by zkjkak** [comment]
I have found the remaining two datasets, but the Yosemite dataset is a high-resolution image and label image. How should I obtain training and testing data? I hope you can provide some suggestions. Thank you very much

**Comment by HAAClassic** [comment]
Hi, according to (https://github.com/nightonion/yosemite-tree-dataset) we separated the Yosemite dataset into 4 subregions (A, B, C, and D) and set the A and C as test data.

**Comment by zkjkak** [comment]
Thank you very much for your help. I have some questions about the Jiangsu dataset that I would like to ask you. I processed the Jiangsu's train and test datasets into the same format as London, and then trained them using your model. However, the MSE obtained was 68, which seems to be far from the effect proposed in your paper. I wonder how you used the Jiangsu dataset for training? Are there any differences between the code you published and it? For example, the parameter or data loading section.

**Comment by HAAClassic** [comment]
According to "https://ieeexplore.ieee.org/document/9509330" the training and test image should have 0.8 m resolution, with the available dataset being about 5 m. We upsampled these images into 512×512 and then cropped the train and test images (256×256). Also, the model converges later than the others for this dataset. As I remember there are no other things!

**Comment by gezixuan721-sys** [comment]
@zkjkak May I ask if you have successfully reproduced it?
