### ISSUE TITLE
Comparison to DeepForest

### ISSUE THREAD

**Issue by bw4sz** [HAAClassic/TreeFormer#7]
Thanks for your really interesting paper. I maintain the DeepForest tree backbone and will be updating it with new data shortly. I'm downloading the datasets from the repo and would like to do a quick check against the model. I already have the Yosemite dataset (see list here: https://github.com/weecology/DeepForest/issues/340), but I don't have the China dataset, where did you find it? I am planning to copy your semi-supervised approach, but probably using a CNN backbone. Did you only try a transformer? Its always unclear to me whether the architecture, data, or training regime was the key element.

**Comment by bw4sz** [comment]
Sorry, just a followup, do you have the raw points and the RGB images, the Data.rar, looks like numpy arrays for the transformer counting network, can I get the point data upstream of that? That way I can overlay it and use it in an object detection pretraining workflow

<img width="1504" alt="image" src="https://github.com/HAAClassic/TreeFormer/assets/1208492/d1d0721e-2e30-43a0-8435-08900fe26cf6">

**Comment by HAAClassic** [comment]
The China dataset is available at: https://github.com/sddpltwanqiu/TreeCountNet/tree/main
No, I checked CNN too,  but I prefer transformer. Also, there are some other papers for tree counting that used CNNs, You can analyze their results.
In my opinion, choosing a suitable model is a necessary condition, while data augmentation is a sufficient condition for improving the model network.
You can overlay them by writing code to plot the point in the specified position of the image. Also, you can convert the point position in the acceptable format of LableMe (JSON file).

**Comment by bw4sz** [comment]
Brilliant, thank you for the clean organization. I wasn't expecting the .mat files to have the points. I thought they were matlab r versions of the numpy arrays of the density maps. My mistake. For anyone coming here later, this is what it looks like:

DeepForest predictions in orange, ground truth in blue.
![output](https://github.com/HAAClassic/TreeFormer/assets/1208492/70f6d257-3693-4249-b3a7-67be5a2e9c3a)
