### ISSUE TITLE
about the density map generation

### ISSUE THREAD

**Issue by SynUW** [HAAClassic/TreeFormer#8]
hi. I have read your paper and code with a lot of interest. However, it is very hard for me to find out how you generate the density map from the labeled points, and what I only saw is the discrete map generation. Could you please help me with that? Many thanks!

**Comment by HAAClassic** [comment]
Hi, you can generate the density maps according to https://github.com/gjy3035/Awesome-Crowd-Counting. There are Matlab and Python codes here for generating density maps.
